version: '3.8'

name: grafana-prometheus

services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/:/var/lib/grafana/
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/:/prometheus/
