version: '3.8'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8443:8443"
    volumes:
        - ./cert.pem:/etc/x509/https/cert.pem
        - ./key.pem:/etc/x509/https/key.pem
    environment:
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      KEYCLOAK_DATABASE_NAME: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_DATABASE_SCHEMA: postgres
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/key.pem
    command:
      - start-dev
    extra_hosts:
       host.docker.internal: "host-gateway"
