version: '3.8'

name: vault

services:
  vault:
    container_name: vault
    image: hashicorp/vault
    ports:
      - 8200:8200
    volumes:
      - ./data/vault/file/:/vault/file:rw
      - ./data/vault/config/:/vault/config:rw
      - ./data/vault/logs/:/vault/logs:rw
      - ./vault-settings.json/:/data/vault/config/local.json:rw
    command:
      - server
    restart: on-failure:3