version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    <<: *default-logging
    restart: on-failure:3
    platform: linux/amd64
    depends_on:
      - redis
      - postgres


  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    <<: *default-logging
    restart: on-failure:3
    platform: linux/amd64
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../../DockerTemplates/data/redis/:/data/
    command: ["redis-server", "/data/redis.conf"]
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../../DockerTemplates/data/postgres/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres